package Clases;
// Generated 12/11/2015 01:31:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idEstudiante;
     private Grado grado;
     private String nombres;
     private String apellidos;
     private long numeroDocumento;
     private String estado;
     private Set fallaprimarias = new HashSet(0);
     private Set fallaareas = new HashSet(0);

    public Estudiante() {
    }
    
    public Vector arrayToVector(){
        Vector lista = new Vector();
        lista.add(this.idEstudiante);
        lista.add(this.grado.getGrado());
        lista.add(this.nombres);
        lista.add(this.apellidos);
        lista.add(this.numeroDocumento);
        lista.add(this.estado);
        return lista;
    }

    public Estudiante(Grado grado, String nombres, String apellidos, long numeroDocumento, String estado) {
        this.grado = grado;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumento = numeroDocumento;
        this.estado = estado;
    }
    
    
	
    public Estudiante(Grado grado, String nombres, String apellidos, long numeroDocumento) {
        this.grado = grado;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumento = numeroDocumento;
        this.estado = estado;
    }
    public Estudiante(Grado grado, String nombres, String apellidos, long numeroDocumento, String estado, Set fallaprimarias, Set fallaareas) {
       this.grado = grado;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numeroDocumento = numeroDocumento;
       this.estado = estado;
       this.fallaprimarias = fallaprimarias;
       this.fallaareas = fallaareas;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public long getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(long numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getFallaprimarias() {
        return this.fallaprimarias;
    }
    
    public void setFallaprimarias(Set fallaprimarias) {
        this.fallaprimarias = fallaprimarias;
    }
    public Set getFallaareas() {
        return this.fallaareas;
    }
    
    public void setFallaareas(Set fallaareas) {
        this.fallaareas = fallaareas;
    }




}


