package Clases;
// Generated 12/11/2015 01:31:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Fallaprimaria generated by hbm2java
 */
public class Fallaprimaria  implements java.io.Serializable {


     private Integer idFallaPrimaria;
     private Estudiante estudiante;
     private String grupo;
     private int codigo;
     private short bimestre;
     private Date fecha;
     private Short inasistencia;

    public Fallaprimaria() {
    }

	
    public Fallaprimaria(Estudiante estudiante, String grupo, int codigo, short bimestre, Date fecha) {
        this.estudiante = estudiante;
        this.grupo = grupo;
        this.codigo = codigo;
        this.bimestre = bimestre;
        this.fecha = fecha;
    }
    public Fallaprimaria(Estudiante estudiante, String grupo, int codigo, short bimestre, Date fecha, Short inasistencia) {
       this.estudiante = estudiante;
       this.grupo = grupo;
       this.codigo = codigo;
       this.bimestre = bimestre;
       this.fecha = fecha;
       this.inasistencia = inasistencia;
    }
   
    public Integer getIdFallaPrimaria() {
        return this.idFallaPrimaria;
    }
    
    public void setIdFallaPrimaria(Integer idFallaPrimaria) {
        this.idFallaPrimaria = idFallaPrimaria;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public short getBimestre() {
        return this.bimestre;
    }
    
    public void setBimestre(short bimestre) {
        this.bimestre = bimestre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Short getInasistencia() {
        return this.inasistencia;
    }
    
    public void setInasistencia(Short inasistencia) {
        this.inasistencia = inasistencia;
    }




}


