package Clases;
// Generated 12/11/2015 01:31:52 PM by Hibernate Tools 4.3.1



/**
 * FallaareaId generated by hbm2java
 */
public class FallaareaId  implements java.io.Serializable {


     private int idFalla;
     private int estudiante;
     private int profesor;

    public FallaareaId() {
    }

    public FallaareaId(int idFalla, int estudiante, int profesor) {
       this.idFalla = idFalla;
       this.estudiante = estudiante;
       this.profesor = profesor;
    }
   
    public int getIdFalla() {
        return this.idFalla;
    }
    
    public void setIdFalla(int idFalla) {
        this.idFalla = idFalla;
    }
    public int getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(int estudiante) {
        this.estudiante = estudiante;
    }
    public int getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(int profesor) {
        this.profesor = profesor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FallaareaId) ) return false;
		 FallaareaId castOther = ( FallaareaId ) other; 
         
		 return (this.getIdFalla()==castOther.getIdFalla())
 && (this.getEstudiante()==castOther.getEstudiante())
 && (this.getProfesor()==castOther.getProfesor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFalla();
         result = 37 * result + this.getEstudiante();
         result = 37 * result + this.getProfesor();
         return result;
   }   


}


