package Clases;
// Generated 12/11/2015 01:31:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private Integer idGrado;
     private String grado;
     private String tipoGrado;
     private String estado;
     private Set estudiantes = new HashSet(0);

    public Grado() {
    }

	
    public Grado(String tipoGrado, String grado) {
        this.tipoGrado = tipoGrado;
        this.grado = grado;
    }
    public Grado(String grado, String estado, Set estudiantes) {
       this.grado = grado;
       this.estado = estado;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(Integer idGrado) {
        this.idGrado = idGrado;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }

    public String getTipoGrado() {
        return tipoGrado;
    }

    public void setTipoGrado(String tipoGrado) {
        this.tipoGrado = tipoGrado;
    }
    
    
    
    
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


