package Clases;
// Generated 12/11/2015 01:31:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idProfesor;
     private String nombres;
     private String apellidos;
     private long numeroDocumento;
     private String estado;
     private Set fallaareas = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(String nombres, String apellidos, long numeroDocumento) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumento = numeroDocumento;
    }
    public Profesor(String nombres, String apellidos, long numeroDocumento, String estado, Set fallaareas) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numeroDocumento = numeroDocumento;
       this.estado = estado;
       this.fallaareas = fallaareas;
    }
   
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public long getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(long numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getFallaareas() {
        return this.fallaareas;
    }
    
    public void setFallaareas(Set fallaareas) {
        this.fallaareas = fallaareas;
    }




}


